verbose: false
instrumentation:
    extensions: [".js",".jsx"]
    root: ./app
    default-excludes: true
    include-all-sources: true
    excludes: ["mocks/**", "**/*.test.jsx*", "**/*.test.js*", "**/index.js", "**/index.jsx", "**/actionTypes/**", "**/sagas/**", "**/app.jsx", "**/*App.jsx", "featureFlags.js", "messagesTexts.js", "preferences.js"]
    variable: __coverage__
reporting:
    print: summary
    reports:
        - lcov
    dir: ./coverage
    watermarks:
        statements: [49.99, 50]
        lines: [49.99, 50]
        functions: [49.99, 50]
        branches: [49.99, 50]
    report-config:
        clover: {file: clover.xml}
        cobertura: {file: cobertura-coverage.xml}
        json: {file: coverage-final.json}
        json-summary: {file: coverage-summary.json}
        lcovonly: {file: lcov.info}
        teamcity: {file: null, blockName: Code Coverage Summary}
        text: {file: null, maxCols: 0}
        text-lcov: {file: lcov.info}
        text-summary: {file: null}
check:
    global:
        statements: 90
        lines: 90
        branches: 90
        functions: 100
        excludes: []
    each:
        statements: 90
        lines: 90
        branches: 90
        functions: 100
        excludes: []
